name: Build

on:
  workflow_call:

jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install rockcraft
        run: |
          sudo snap install --classic --channel edge rockcraft
      - name: Build ROCK
        run: rockcraft pack --verbose

      - name: Upload locally built ROCK artifact
        uses: actions/upload-artifact@v3
        with:
          name: ory-hydra-rock
          path: "ory-hydra_*.rock"
